---
kind: "Template"
apiVersion: "v1"
objects:
 -  apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: app-server-deployment
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: app-server
        spec:
          containers:
          - name: app-server
            image: gcr.io/$(GCLOUD_PROJECT_ID)/app-server:$(TAG)
            imagePullPolicy: IfNotPresent
            env:
            - name: GCLOUD_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: codegp-config
                  key: gcloud-project-id
            - name: IS_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: codegp-config
                  key: is-local
            - name: DATASTORE_EMULATOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: codegp-config
                  key: datastore-emulator-host
            ports:
            - containerPort: 8080
            volumeMounts:
            - mountPath: /localstore
              name: localstore-volume
              readOnly: false
          volumes:
          - name: localstore-volume
            hostPath:
              # directory location on host
              path: /localstore

parameters:
- name: "GCLOUD_PROJECT_ID"
  description: "gcloud project id "
  value: "local"
  required: false
  parameterType: "string"
- name: "TAG"
  description: "image tag"
  value: "latest"
  required: false
  parameterType: "string"
