apiVersion: v1
kind: Service
metadata:
  name: localfs-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31002
  selector:
    app: localfs

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: localfs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: localfs
    spec:
      containers:
      - name: localfs
        image: codegp/localfs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /localstore
          name: localstore-volume
          readOnly: true
      volumes:
      - name: localstore-volume
        hostPath:
          # directory location on host
          path: /localstore
